# Repository settings for GitHub Copilot Agent support
# This file can be used with probot/settings app to configure repository settings

repository:
  # Enable features that GitHub Copilot agent needs
  has_issues: true
  has_projects: true
  has_wiki: false
  
  # Enable merge options
  allow_merge_commit: true
  allow_squash_merge: true
  allow_rebase_merge: true
  
  # Enable automatic deletion of head branches
  delete_branch_on_merge: true

# Branch protection rules
branches:
  - name: main
    protection:
      # Enable GitHub Copilot agent to create pull requests
      required_status_checks:
        strict: true
        contexts:
          - "build"
      
      # Allow GitHub Apps (including Copilot) to bypass restrictions
      restrictions:
        apps: []
        users: []
        teams: []
      
      # Enable pull request reviews
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false