blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/tomasforsman/Vivaldi-Mod-Manager/blob/main/README.md
    about: Check the documentation first for common questions
  - name: 💬 Discussions
    url: https://github.com/tomasforsman/Vivaldi-Mod-Manager/discussions
    about: Ask questions and discuss ideas with the community